import { EVModel } from '../src/types/ev';

export const evData: EVModel[] = [
  {
    id: "hyundai-ioniq-5",
    brand: "Hyundai",
    model: "Ioniq 5",
    year: 2024,
    price_range: { min: 782000000, max: 895000000 },
    priceFormatted: "Rp 782 Juta - 895 Juta",
    battery_capacity: 72.6,
    range_claimed: 481,
    range_real_world: 430,
    charging_time: { ac: 6.1, dc: 0.3 }, // 18 mins DC
    fastChargeTimeMins: 18,
    motor_power: 160,
    torque: 350,
    seating_capacity: 5,
    cargo_volume: 527,
    ground_clearance: 160,
    warranty: { years: 8, km: 160000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1671207604603-78fca554ff1a?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.hyundai.com/id/id/build-a-car/ioniq5",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan", "Bali"],
    incentives: ["PPnBM 1%"],
    category: "suv",
    bodyType: "SUV",
    tags: ["family", "luxury", "commuter"],
    pros: ["Desain futuristik retro", "Kabin sangat luas", "Fitur V2L sangat berguna"],
    cons: ["Radius putar cukup besar", "Tanpa wiper belakang"],
    suitability: ["Keluarga", "Perjalanan Jauh", "Pengguna Teknologi"],
    service_center: "Sangat Luas (Hyundai 100+ Dealer)"
  },
  {
    id: "hyundai-ioniq-6",
    brand: "Hyundai",
    model: "Ioniq 6",
    year: 2024,
    price_range: { min: 1197000000, max: 1197000000 },
    priceFormatted: "Rp 1.19 Milyar",
    battery_capacity: 77.4,
    range_claimed: 519,
    range_real_world: 480,
    charging_time: { ac: 7.1, dc: 0.3 },
    fastChargeTimeMins: 18,
    motor_power: 239,
    torque: 605,
    seating_capacity: 5,
    cargo_volume: 401,
    ground_clearance: 141,
    warranty: { years: 8, km: 160000 },
    made_in: "South Korea",
    images: ["https://images.unsplash.com/photo-1689255767852-c62cbac6b5eb?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.hyundai.com/id/id/build-a-car/ioniq6",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan", "Bali"],
    incentives: [],
    category: "sedan",
    bodyType: "Sedan",
    tags: ["luxury", "performance"],
    pros: ["Aerodinamika sangat baik", "Jarak tempuh jauh", "Percepatan instan"],
    cons: ["Headroom baris kedua terbatas", "Bagasi tidak terlalu besar"],
    suitability: ["Eksekutif", "Penggemar Kecepatan"],
    service_center: "Sangat Luas (Hyundai 100+ Dealer)"
  },
  {
    id: "hyundai-kona-electric",
    brand: "Hyundai",
    model: "Kona Electric",
    year: 2024,
    price_range: { min: 499000000, max: 590000000 },
    priceFormatted: "Rp 499 Juta - 590 Juta",
    battery_capacity: 65.4,
    range_claimed: 514,
    range_real_world: 450,
    charging_time: { ac: 6.5, dc: 0.7 },
    fastChargeTimeMins: 43,
    motor_power: 160,
    torque: 255,
    seating_capacity: 5,
    cargo_volume: 466,
    ground_clearance: 158,
    warranty: { years: 8, km: 160000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1700473950275-52ce6d6efcd5?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.hyundai.com/id",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan", "Bali"],
    incentives: ["PPnBM 1%"],
    category: "suv",
    bodyType: "SUV",
    tags: ["family", "commuter", "city"],
    pros: ["Jarak tempuh impresif", "Harga kompetitif untuk baterai lokal", "Desain modern"],
    cons: ["Torsi lebih rendah dari versi lama", "Material interior banyak plastik keras"],
    suitability: ["Keluarga Muda", "Pengguna Harian"],
    service_center: "Sangat Luas (Hyundai 100+ Dealer)"
  },
  {
    id: "wuling-air-ev",
    brand: "Wuling",
    model: "Air EV",
    year: 2024,
    price_range: { min: 206000000, max: 299500000 },
    priceFormatted: "Rp 206 Juta - 299 Juta",
    battery_capacity: 26.7,
    range_claimed: 300,
    range_real_world: 250,
    charging_time: { ac: 4.0, dc: null },
    fastChargeTimeMins: null,
    motor_power: 30,
    torque: 110,
    seating_capacity: 4,
    cargo_volume: 0, 
    ground_clearance: 130,
    warranty: { years: 8, km: 120000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1698380290196-8eb5db21d030?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://wuling.id/id/air-ev",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Bali"],
    incentives: ["PPnBM 1%"],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["budget", "commuter", "city"],
    pros: ["Ukuran sangat ringkas untuk parkir", "Harga sangat terjangkau", "Biaya operasional rendah"],
    cons: ["Tidak ada fast charging DC", "Kapasitas penumpang/bagasi sangat minim", "Suspensi keras"],
    suitability: ["Mahasiswa", "Ibu Rumah Tangga", "Komuter Kota"],
    service_center: "Luas (Wuling 150+ Dealer)"
  },
  {
    id: "wuling-binguo-ev",
    brand: "Wuling",
    model: "BinguoEV",
    year: 2024,
    price_range: { min: 317000000, max: 372000000 },
    priceFormatted: "Rp 317 Juta - 372 Juta",
    battery_capacity: 31.9,
    range_claimed: 333,
    range_real_world: 280,
    charging_time: { ac: 5.5, dc: 0.6 },
    fastChargeTimeMins: 35,
    motor_power: 50,
    torque: 150,
    seating_capacity: 5,
    cargo_volume: 310,
    ground_clearance: 135,
    warranty: { years: 8, km: 120000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1698380290196-8eb5db21d030?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://wuling.id/id/binguo-ev",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Bali"],
    incentives: ["PPnBM 1%", "Lifetime Battery Warranty"],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["family", "commuter"],
    pros: ["Desain retro klasik menarik", "Kabin cukup lega", "Mendukung DC Charging"],
    cons: ["Performa motor biasa saja", "Material interior tergolong basic"],
    suitability: ["Keluarga Kecil", "Komuter Harian"],
    service_center: "Luas (Wuling 150+ Dealer)"
  },
  {
    id: "wuling-cloud-ev",
    brand: "Wuling",
    model: "Cloud EV",
    year: 2024,
    price_range: { min: 398000000, max: 398000000 },
    priceFormatted: "Rp 398 Juta",
    battery_capacity: 50.6,
    range_claimed: 460,
    range_real_world: 400,
    charging_time: { ac: 7.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 100,
    torque: 200,
    seating_capacity: 5,
    cargo_volume: 606,
    ground_clearance: 150,
    warranty: { years: 8, km: 120000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1698380290196-8eb5db21d030?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://wuling.id/id/cloud-ev",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Bali"],
    incentives: ["PPnBM 1%", "Lifetime Battery Warranty"],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["family", "comfort"],
    pros: ["Jok ala sofa sangat nyaman", "Bagasi sangat luas", "Range cukup jauh"],
    cons: ["Desain eksterior membulat kurang sporty", "Handling bukan yang terbaik"],
    suitability: ["Keluarga", "Perjalanan Jauh Nyaman"],
    service_center: "Luas (Wuling 150+ Dealer)"
  },
  {
    id: "byd-dolphin",
    brand: "BYD",
    model: "Dolphin",
    year: 2024,
    price_range: { min: 425000000, max: 425000000 },
    priceFormatted: "Rp 425 Juta",
    battery_capacity: 60.48,
    range_claimed: 490,
    range_real_world: 420,
    charging_time: { ac: 6.0, dc: 0.5 },
    fastChargeTimeMins: 29,
    motor_power: 150,
    torque: 310,
    seating_capacity: 5,
    cargo_volume: 345,
    ground_clearance: 130,
    warranty: { years: 8, km: 160000 },
    made_in: "China",
    images: ["https://images.unsplash.com/photo-1707227155609-5b91a766418d?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://byd-indonesia.co.id/dolphin",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["commuter", "family"],
    pros: ["Performa motor luar biasa (201 hp)", "Blade battery aman", "Interior modern layar putar"],
    cons: ["Ground clearance rendah", "Bentuk eksterior mungkin kurang disukai sebagian orang"],
    suitability: ["Keluarga Muda", "Pengguna Harian"],
    service_center: "Menengah (BYD Terus Ekspansi)"
  },
  {
    id: "byd-atto-3",
    brand: "BYD",
    model: "Atto 3",
    year: 2024,
    price_range: { min: 515000000, max: 515000000 },
    priceFormatted: "Rp 515 Juta",
    battery_capacity: 60.48,
    range_claimed: 480,
    range_real_world: 410,
    charging_time: { ac: 6.0, dc: 0.5 },
    fastChargeTimeMins: 29,
    motor_power: 150,
    torque: 310,
    seating_capacity: 5,
    cargo_volume: 440,
    ground_clearance: 175,
    warranty: { years: 8, km: 160000 },
    made_in: "China",
    images: ["https://images.unsplash.com/photo-1707227155609-5b91a766418d?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://byd-indonesia.co.id/atto-3",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["family", "commuter"],
    pros: ["Desain SUV kompak disukai pasar", "Kabin interior bertema gym yang unik", "Fitur ADAS lengkap"],
    cons: ["Desain interior mungkin terlalu eksentrik", "Jaringan dealer belum merata"],
    suitability: ["Keluarga", "Perjalanan Dalam/Luar Kota"],
    service_center: "Menengah (BYD Terus Ekspansi)"
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "Seal",
    year: 2024,
    price_range: { min: 629000000, max: 719000000 },
    priceFormatted: "Rp 629 Juta - 719 Juta",
    battery_capacity: 82.56,
    range_claimed: 580,
    range_real_world: 500,
    charging_time: { ac: 8.0, dc: 0.4 },
    fastChargeTimeMins: 26,
    motor_power: 390,
    torque: 670,
    seating_capacity: 5,
    cargo_volume: 400,
    ground_clearance: 120,
    warranty: { years: 8, km: 160000 },
    made_in: "China",
    images: ["https://images.unsplash.com/photo-1695420377508-8e6f1f2e1cbb?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://byd-indonesia.co.id/seal",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "sedan",
    bodyType: "Sedan",
    tags: ["performance", "luxury"],
    pros: ["Akselerasi 0-100 km/j dalam 3.8s (AWD)", "Desain sangat sporty", "Kualitas interior premium"],
    cons: ["Ground clearance sangat rendah", "Headroom baris kedua sempit"],
    suitability: ["Penggemar Kecepatan", "Eksekutif Muda"],
    service_center: "Menengah (BYD Terus Ekspansi)"
  },
  {
    id: "vinfast-vf-5",
    brand: "VinFast",
    model: "VF 5",
    year: 2024,
    price_range: { min: 242000000, max: 242000000 },
    priceFormatted: "Rp 242 Juta",
    battery_capacity: 37.2,
    range_claimed: 326,
    range_real_world: 270,
    charging_time: { ac: 6.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 100,
    torque: 135,
    seating_capacity: 5,
    cargo_volume: 260,
    ground_clearance: 182,
    warranty: { years: 7, km: 160000 },
    made_in: "Vietnam",
    images: ["https://images.unsplash.com/photo-1700473950275-52ce6d6efcd5?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://vinfastauto.id/vf5",
    dealer_network: ["Jakarta"],
    incentives: ["Battery Subscription Available"],
    category: "suv",
    bodyType: "SUV",
    tags: ["budget", "city"],
    pros: ["Harga mobil sangat murah", "Garansi panjang", "Model SUV"],
    cons: ["Biaya sewa baterai bulanan", "Merek baru di Indonesia"],
    suitability: ["Komuter Kota", "Pencari Harga Miring"],
    service_center: "Terbatas (Baru Masuk)"
  },
  {
    id: "vinfast-vf-e34",
    brand: "VinFast",
    model: "VF e34",
    year: 2024,
    price_range: { min: 315000000, max: 315000000 },
    priceFormatted: "Rp 315 Juta",
    battery_capacity: 41.9,
    range_claimed: 318,
    range_real_world: 260,
    charging_time: { ac: 6.0, dc: 0.5 },
    fastChargeTimeMins: 27,
    motor_power: 110,
    torque: 242,
    seating_capacity: 5,
    cargo_volume: 290,
    ground_clearance: 180,
    warranty: { years: 10, km: 200000 },
    made_in: "Vietnam",
    images: ["https://images.unsplash.com/photo-1700473950275-52ce6d6efcd5?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://vinfastauto.id/vfe34",
    dealer_network: ["Jakarta"],
    incentives: ["Battery Subscription Available"],
    category: "suv",
    bodyType: "SUV",
    tags: ["family", "commuter"],
    pros: ["Kabin lebih lega dari VF5", "Fitur smart assistant", "Harga entry level"],
    cons: ["Sewa baterai wajib dipertimbangkan", "Desain interior kurang wah"],
    suitability: ["Keluarga Kecil", "Dalam Kota"],
    service_center: "Terbatas (Baru Masuk)"
  },
  {
    id: "mg-4-ev",
    brand: "MG",
    model: "MG4 EV",
    year: 2024,
    price_range: { min: 433000000, max: 433000000 },
    priceFormatted: "Rp 433 Juta",
    battery_capacity: 51.0,
    range_claimed: 425,
    range_real_world: 350,
    charging_time: { ac: 5.0, dc: 0.4 },
    fastChargeTimeMins: 26,
    motor_power: 125,
    torque: 250,
    seating_capacity: 5,
    cargo_volume: 363,
    ground_clearance: 150,
    warranty: { years: 8, km: 160000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1692186716075-817ab5da8564?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://mgmotor.id/mg4-ev",
    dealer_network: ["Jakarta", "Surabaya", "Bandung"],
    incentives: ["PPnBM 1%"],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["performance", "family"],
    pros: ["Handling luar biasa dengan RWD", "Desain tajam dan agresif", "Value for money tinggi"],
    cons: ["Bentuk setir kurang nyaman untuk sebagian orang", "Head unit agak lambat"],
    suitability: ["Penggemar Mengemudi", "Keluarga Muda"],
    service_center: "Menengah (MG Dealer Tersebar)"
  },
  {
    id: "mg-zs-ev",
    brand: "MG",
    model: "ZS EV",
    year: 2024,
    price_range: { min: 453000000, max: 453000000 },
    priceFormatted: "Rp 453 Juta",
    battery_capacity: 50.3,
    range_claimed: 403,
    range_real_world: 340,
    charging_time: { ac: 5.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 130,
    torque: 280,
    seating_capacity: 5,
    cargo_volume: 448,
    ground_clearance: 161,
    warranty: { years: 8, km: 160000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1692186716075-817ab5da8564?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://mgmotor.id/zs-ev",
    dealer_network: ["Jakarta", "Surabaya", "Bandung"],
    incentives: ["PPnBM 1%"],
    category: "suv",
    bodyType: "SUV",
    tags: ["family", "commuter"],
    pros: ["Desain SUV konvensional disukai banyak orang", "Kabin lapang", "Panoramic sunroof besar"],
    cons: ["Platform bukan pure EV (konversi dari ICE)", "Range tidak sebesar MG4"],
    suitability: ["Keluarga", "Perjalanan Kota/Luar Kota"],
    service_center: "Menengah (MG Dealer Tersebar)"
  },
  {
    id: "mg-maxus-9",
    brand: "MG",
    model: "Maxus 9",
    year: 2024,
    price_range: { min: 1425000000, max: 1425000000 },
    priceFormatted: "Rp 1.42 Milyar",
    battery_capacity: 90.0,
    range_claimed: 540,
    range_real_world: 480,
    charging_time: { ac: 9.0, dc: 0.6 },
    fastChargeTimeMins: 36,
    motor_power: 180,
    torque: 350,
    seating_capacity: 7,
    cargo_volume: 500,
    ground_clearance: 140,
    warranty: { years: 8, km: 160000 },
    made_in: "Thailand",
    images: ["https://images.unsplash.com/photo-1692186716075-817ab5da8564?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://mgmotor.id/maxus-9",
    dealer_network: ["Jakarta", "Surabaya", "Bandung"],
    incentives: [],
    category: "mpv",
    bodyType: "MPV",
    tags: ["luxury", "family"],
    pros: ["Kenyamanan VIP seat luar biasa", "Kabin sangat senyap", "MPV listrik premium langka"],
    cons: ["Harga premium", "Ukuran sangat besar, repot parkir"],
    suitability: ["VVIP", "Keluarga Besar Eksklusif"],
    service_center: "Menengah (MG Dealer Tersebar)"
  },
  {
    id: "toyota-bz4x",
    brand: "Toyota",
    model: "bZ4X",
    year: 2024,
    price_range: { min: 1190000000, max: 1190000000 },
    priceFormatted: "Rp 1.19 Milyar",
    battery_capacity: 71.4,
    range_claimed: 500,
    range_real_world: 420,
    charging_time: { ac: 7.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 150,
    torque: 266,
    seating_capacity: 5,
    cargo_volume: 452,
    ground_clearance: 210,
    warranty: { years: 8, km: 160000 },
    made_in: "Japan",
    images: ["https://images.unsplash.com/photo-1698226065545-21d4c2b9a117?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.toyota.astra.co.id/bz4x",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan", "Makassar"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["luxury", "family"],
    pros: ["Jaringan bengkel terbaik Toyota", "Ground clearance tinggi", "Desain kokoh"],
    cons: ["Harga lebih tinggi dibanding kompetitor (Ioniq 5)", "Kapasitas fast charge kalah cepat"],
    suitability: ["Loyalis Toyota", "Perjalanan Semua Medan"],
    service_center: "Sangat Luas (Toyota 300+ Dealer)"
  },
  {
    id: "chery-omoda-e5",
    brand: "Chery",
    model: "Omoda E5",
    year: 2024,
    price_range: { min: 488800000, max: 488800000 },
    priceFormatted: "Rp 488.8 Juta",
    battery_capacity: 61.06,
    range_claimed: 430,
    range_real_world: 360,
    charging_time: { ac: 6.0, dc: 0.5 },
    fastChargeTimeMins: 28,
    motor_power: 150,
    torque: 340,
    seating_capacity: 5,
    cargo_volume: 380,
    ground_clearance: 190,
    warranty: { years: 8, km: 160000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1707328637042-3a05be4dd6cd?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://chery.co.id/omoda-e5",
    dealer_network: ["Jakarta", "Surabaya", "Bandung"],
    incentives: ["PPnBM 1%", "Lifetime Battery Warranty"],
    category: "suv",
    bodyType: "SUV",
    tags: ["performance", "luxury"],
    pros: ["Desain sangat agresif", "Performa kencang dan halus", "Chipset Snapdragon canggih di Head Unit"],
    cons: ["Feedback setir kurang natural", "Bagasi tidak seluas lawan sekelasnya"],
    suitability: ["Anak Muda", "Pengguna Teknologi"],
    service_center: "Menengah (Chery Ekspansi)"
  },
  {
    id: "dfsk-gelora-e",
    brand: "DFSK",
    model: "Gelora E",
    year: 2024,
    price_range: { min: 350000000, max: 399000000 },
    priceFormatted: "Rp 350 Juta - 399 Juta",
    battery_capacity: 42.0,
    range_claimed: 300,
    range_real_world: 230,
    charging_time: { ac: 8.0, dc: 1.5 },
    fastChargeTimeMins: 90,
    motor_power: 60,
    torque: 200,
    seating_capacity: 11,
    cargo_volume: 4800,
    ground_clearance: 200,
    warranty: { years: 5, km: 120000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1698380290196-8eb5db21d030?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.dfskmotors.co.id/gelora-e",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: ["PPnBM 1%"],
    category: "commercial",
    bodyType: "MPV",
    tags: ["budget", "commercial"],
    pros: ["Satu-satunya van listrik terjangkau", "Kapasitas muatan sangat besar", "Tersedia blind van"],
    cons: ["Fitur sangat basic", "Desain jadul", "Material interior murahan"],
    suitability: ["Fleet Usaha", "Logistik", "Travel"],
    service_center: "Terbatas (DFSK/Seres)"
  },
  {
    id: "dfsk-seres-e1",
    brand: "Seres",
    model: "E1",
    year: 2024,
    price_range: { min: 189000000, max: 219000000 },
    priceFormatted: "Rp 189 Juta - 219 Juta",
    battery_capacity: 16.8,
    range_claimed: 220,
    range_real_world: 180,
    charging_time: { ac: 4.0, dc: null },
    fastChargeTimeMins: null,
    motor_power: 25,
    torque: 100,
    seating_capacity: 4,
    cargo_volume: 0,
    ground_clearance: 135,
    warranty: { years: 8, km: 120000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1698380290196-8eb5db21d030?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.dfskmotors.co.id",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: ["PPnBM 1%"],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["budget", "city"],
    pros: ["Harga paling murah di pasaran", "Ukuran mini cocok untuk parkir sempit"],
    cons: ["Baterai sangat kecil", "Tidak ada fast charging"],
    suitability: ["Komuter Jarak Dekat", "Mahasiswa"],
    service_center: "Terbatas (DFSK/Seres)"
  },
  {
    id: "nissan-leaf",
    brand: "Nissan",
    model: "Leaf",
    year: 2024,
    price_range: { min: 738000000, max: 738000000 },
    priceFormatted: "Rp 738 Juta",
    battery_capacity: 40.0,
    range_claimed: 311,
    range_real_world: 250,
    charging_time: { ac: 7.0, dc: 0.6 },
    fastChargeTimeMins: 40,
    motor_power: 110,
    torque: 320,
    seating_capacity: 5,
    cargo_volume: 435,
    ground_clearance: 150,
    warranty: { years: 8, km: 160000 },
    made_in: "Japan",
    images: ["https://images.unsplash.com/photo-1593941707882-a5bba14938c7?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.nissan.co.id/vehicles/new/leaf.html",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan"],
    incentives: [],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["family", "commuter"],
    pros: ["Reputasi EV yang proven (pioneer)", "Kenyamanan khas mobil Jepang"],
    cons: ["Port charging CHAdeMO kurang lazim di RI", "Range kecil untuk harganya", "Baterai pasif cooling"],
    suitability: ["Loyalis Nissan", "Dalam Kota"],
    service_center: "Luas (Nissan Dealer)"
  },
  {
    id: "kia-ev6",
    brand: "Kia",
    model: "EV6",
    year: 2024,
    price_range: { min: 1299000000, max: 1699000000 },
    priceFormatted: "Rp 1.29 Milyar - 1.69 Milyar",
    battery_capacity: 77.4,
    range_claimed: 506,
    range_real_world: 460,
    charging_time: { ac: 7.0, dc: 0.3 },
    fastChargeTimeMins: 18,
    motor_power: 239,
    torque: 605,
    seating_capacity: 5,
    cargo_volume: 520,
    ground_clearance: 160,
    warranty: { years: 8, km: 160000 },
    made_in: "South Korea",
    images: ["https://images.unsplash.com/photo-1663155700755-e7fdf13bf78b?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.kia.com/id/models/ev6/features.html",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["performance", "luxury"],
    pros: ["Desain sangat memukau dan agresif", "Varian GT sangat beringas (576 hp)", "Teknologi 800V fast charging"],
    cons: ["Harga lebih mahal dari Ioniq 5 dengan platform sama", "Jaringan dealer Kia tidak seluas Hyundai"],
    suitability: ["Penggemar Performa", "Desain Aficionado"],
    service_center: "Menengah (Kia Indomobil)"
  },
  {
    id: "kia-ev9",
    brand: "Kia",
    model: "EV9",
    year: 2024,
    price_range: { min: 1975000000, max: 1975000000 },
    priceFormatted: "Rp 1.97 Milyar",
    battery_capacity: 99.8,
    range_claimed: 497,
    range_real_world: 440,
    charging_time: { ac: 9.0, dc: 0.4 },
    fastChargeTimeMins: 24,
    motor_power: 283,
    torque: 700,
    seating_capacity: 6,
    cargo_volume: 828,
    ground_clearance: 177,
    warranty: { years: 8, km: 160000 },
    made_in: "South Korea",
    images: ["https://images.unsplash.com/photo-1663155700755-e7fdf13bf78b?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.kia.com/id/models/ev9/features.html",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["luxury", "family"],
    pros: ["3-row seating SUV listrik sesungguhnya", "Kursi swivel baris kedua", "Desain boxy maskulin"],
    cons: ["Dimensi sangat besar", "Konsumsi daya boros karena berat"],
    suitability: ["Keluarga Besar VVIP", "Sultan"],
    service_center: "Menengah (Kia Indomobil)"
  },
  {
    id: "bmw-ix",
    brand: "BMW",
    model: "iX",
    year: 2024,
    price_range: { min: 2428000000, max: 2428000000 },
    priceFormatted: "Rp 2.42 Milyar",
    battery_capacity: 76.6,
    range_claimed: 390,
    range_real_world: 350,
    charging_time: { ac: 7.5, dc: 0.5 },
    fastChargeTimeMins: 31,
    motor_power: 240,
    torque: 630,
    seating_capacity: 5,
    cargo_volume: 500,
    ground_clearance: 202,
    warranty: { years: 8, km: 160000 },
    made_in: "Germany",
    images: ["https://images.unsplash.com/photo-1663155700755-e7fdf13bf78b?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.bmw.co.id",
    dealer_network: ["Jakarta", "Surabaya", "Medan", "Bali"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["luxury", "performance"],
    pros: ["Kenyamanan dan kualitas material tingkat dewa", "Suspensi udara sangat empuk", "Desain interior lounge-like"],
    cons: ["Grill depan kontroversial", "Jarak tempuh versi xDrive40 terbatas untuk harga ini"],
    suitability: ["Eksekutif", "Penggemar Luxury"],
    service_center: "Eksklusif (BMW Eurokars/Tunas/Astra)"
  },
  {
    id: "bmw-i4",
    brand: "BMW",
    model: "i4",
    year: 2024,
    price_range: { min: 2108000000, max: 2108000000 },
    priceFormatted: "Rp 2.10 Milyar",
    battery_capacity: 83.9,
    range_claimed: 590,
    range_real_world: 510,
    charging_time: { ac: 8.5, dc: 0.5 },
    fastChargeTimeMins: 31,
    motor_power: 250,
    torque: 430,
    seating_capacity: 5,
    cargo_volume: 470,
    ground_clearance: 125,
    warranty: { years: 8, km: 160000 },
    made_in: "Germany",
    images: ["https://images.unsplash.com/photo-1689255767852-c62cbac6b5eb?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.bmw.co.id",
    dealer_network: ["Jakarta", "Surabaya", "Medan"],
    incentives: [],
    category: "sedan",
    bodyType: "Sedan",
    tags: ["luxury", "performance"],
    pros: ["Handling layaknya BMW ICE sejati", "Range yang baik", "Bentuk Gran Coupe yang sangat keren"],
    cons: ["Kabin belakang cukup sempit", "Masih ada tunnel gardan karena platform berbagi dengan Seri-4"],
    suitability: ["Eksekutif Muda", "Penggemar Nyetir Sendiri"],
    service_center: "Eksklusif (BMW Astra)"
  },
  {
    id: "bmw-i7",
    brand: "BMW",
    model: "i7",
    year: 2024,
    price_range: { min: 3285000000, max: 3285000000 },
    priceFormatted: "Rp 3.28 Milyar",
    battery_capacity: 101.7,
    range_claimed: 625,
    range_real_world: 550,
    charging_time: { ac: 10.0, dc: 0.5 },
    fastChargeTimeMins: 34,
    motor_power: 400,
    torque: 745,
    seating_capacity: 5,
    cargo_volume: 500,
    ground_clearance: 136,
    warranty: { years: 8, km: 160000 },
    made_in: "Germany",
    images: ["https://images.unsplash.com/photo-1663155700755-e7fdf13bf78b?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.bmw.co.id",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "sedan",
    bodyType: "Sedan",
    tags: ["luxury", "performance"],
    pros: ["Kenyamanan paripurna", "Theater screen 31 inci di baris kedua", "Kekedapan suara terbaik"],
    cons: ["Harga sangat fantastis", "Desain exterior polarizing"],
    suitability: ["Sultan", "Direktur Utama", "Pejabat"],
    service_center: "Eksklusif (BMW Eurokars)"
  },
  {
    id: "lexus-ux300e",
    brand: "Lexus",
    model: "UX300e",
    year: 2024,
    price_range: { min: 1524000000, max: 1524000000 },
    priceFormatted: "Rp 1.52 Milyar",
    battery_capacity: 72.8,
    range_claimed: 450,
    range_real_world: 380,
    charging_time: { ac: 7.0, dc: 1.0 },
    fastChargeTimeMins: 80,
    motor_power: 150,
    torque: 300,
    seating_capacity: 5,
    cargo_volume: 314,
    ground_clearance: 140,
    warranty: { years: 8, km: 160000 },
    made_in: "Japan",
    images: ["https://images.unsplash.com/photo-1698226065545-21d4c2b9a117?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.lexus.co.id",
    dealer_network: ["Jakarta"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["luxury", "commuter"],
    pros: ["Build quality khas Lexus", "Layanan purna jual Lexus yang tak tertandingi", "Baterai versi baru lebih besar"],
    cons: ["Platform ICE konversi", "Port CHAdeMO", "Ruang belakang sempit"],
    suitability: ["Eksekutif", "Sosialita Kota"],
    service_center: "Eksklusif (Lexus Gallery)"
  },
  {
    id: "lexus-rz",
    brand: "Lexus",
    model: "RZ",
    year: 2024,
    price_range: { min: 2287000000, max: 2287000000 },
    priceFormatted: "Rp 2.28 Milyar",
    battery_capacity: 71.4,
    range_claimed: 400,
    range_real_world: 330,
    charging_time: { ac: 7.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 230,
    torque: 435,
    seating_capacity: 5,
    cargo_volume: 522,
    ground_clearance: 200,
    warranty: { years: 8, km: 160000 },
    made_in: "Japan",
    images: ["https://images.unsplash.com/photo-1698226065545-21d4c2b9a117?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.lexus.co.id",
    dealer_network: ["Jakarta"],
    incentives: [],
    category: "suv",
    bodyType: "SUV",
    tags: ["luxury", "family"],
    pros: ["Desain sangat memukau", "Sistem AWD Direct4 sangat halus", "Radiant heater system hemat daya"],
    cons: ["Range tergolong pendek untuk harganya", "Tidak ada glovebox tradisional"],
    suitability: ["Keluarga Mapan", "Eksekutif"],
    service_center: "Eksklusif (Lexus Gallery)"
  },
  {
    id: "mini-electric",
    brand: "MINI",
    model: "Electric",
    year: 2024,
    price_range: { min: 1046000000, max: 1046000000 },
    priceFormatted: "Rp 1.04 Milyar",
    battery_capacity: 32.6,
    range_claimed: 232,
    range_real_world: 180,
    charging_time: { ac: 4.0, dc: 0.5 },
    fastChargeTimeMins: 36,
    motor_power: 135,
    torque: 270,
    seating_capacity: 4,
    cargo_volume: 211,
    ground_clearance: 128,
    warranty: { years: 8, km: 100000 },
    made_in: "UK",
    images: ["https://images.unsplash.com/photo-1707227155609-5b91a766418d?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.mini.co.id",
    dealer_network: ["Jakarta", "Surabaya"],
    incentives: [],
    category: "hatchback",
    bodyType: "Hatchback",
    tags: ["performance", "city"],
    pros: ["Go-kart handling murni MINI", "Desain iconic", "Sangat fun to drive"],
    cons: ["Baterai sangat kecil", "Hanya cocok untuk rute dalam kota"],
    suitability: ["Fashion Statement", "City Commuter Mewah"],
    service_center: "Eksklusif (BMW-MINI Network)"
  },
  {
    id: "neta-v",
    brand: "Neta",
    model: "V",
    year: 2024,
    price_range: { min: 317000000, max: 317000000 },
    priceFormatted: "Rp 317 Juta",
    battery_capacity: 40.7,
    range_claimed: 401,
    range_real_world: 320,
    charging_time: { ac: 8.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 70,
    torque: 150,
    seating_capacity: 5,
    cargo_volume: 335,
    ground_clearance: 130,
    warranty: { years: 8, km: 160000 },
    made_in: "China",
    images: ["https://images.unsplash.com/photo-1700473950275-52ce6d6efcd5?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://neta.co.id",
    dealer_network: ["Jakarta"],
    incentives: ["PPnBM 1%"],
    category: "suv",
    bodyType: "SUV",
    tags: ["budget", "commuter"],
    pros: ["Harga murah", "Layar head unit sangat besar", "Kabin lapang"],
    cons: ["Setir tidak bisa teleskopik/tilt", "Desain eksterior cukup polarisasi"],
    suitability: ["Komuter Kota", "Pencari Value"],
    service_center: "Terbatas (Sedang Ekspansi)"
  },
  {
    id: "neta-v-ii",
    brand: "Neta",
    model: "V-II",
    year: 2024,
    price_range: { min: 299000000, max: 299000000 },
    priceFormatted: "Rp 299 Juta",
    battery_capacity: 36.1,
    range_claimed: 401,
    range_real_world: 310,
    charging_time: { ac: 8.0, dc: 0.5 },
    fastChargeTimeMins: 30,
    motor_power: 70,
    torque: 150,
    seating_capacity: 5,
    cargo_volume: 335,
    ground_clearance: 130,
    warranty: { years: 8, km: 160000 },
    made_in: "Indonesia",
    images: ["https://images.unsplash.com/photo-1700473950275-52ce6d6efcd5?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://neta.co.id",
    dealer_network: ["Jakarta"],
    incentives: ["PPnBM 1%"],
    category: "suv",
    bodyType: "SUV",
    tags: ["budget", "commuter"],
    pros: ["Dirakit lokal (CKD) jadi lebih murah", "Baterai LFP lebih aman", "Interior diperbarui"],
    cons: ["Sama seperti V, posisi duduk agak canggung"],
    suitability: ["Keluarga Kecil", "Komuter Kota"],
    service_center: "Terbatas (Sedang Ekspansi)"
  },
  {
    id: "mercedes-eqe-350",
    brand: "Mercedes-Benz",
    model: "EQE 350+",
    year: 2024,
    price_range: { min: 2215000000, max: 2215000000 },
    priceFormatted: "Rp 2.21 Milyar",
    battery_capacity: 90.6,
    range_claimed: 660,
    range_real_world: 550,
    charging_time: { ac: 8.0, dc: 0.5 },
    fastChargeTimeMins: 32,
    motor_power: 215,
    torque: 565,
    seating_capacity: 5,
    cargo_volume: 430,
    ground_clearance: 135,
    warranty: { years: 10, km: 250000 },
    made_in: "Germany",
    images: ["https://images.unsplash.com/photo-1689255767852-c62cbac6b5eb?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.mercedes-benz.co.id",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan"],
    incentives: [],
    category: "sedan",
    bodyType: "Sedan",
    tags: ["luxury", "performance"],
    pros: ["Range sangatt jauh", "Interior mewah dengan ambient light kelas atas", "Sangat kedap"],
    cons: ["Bentuk jelly bean kurang agresif", "Visibilitas belakang kurang"],
    suitability: ["Eksekutif C-Level", "Perjalanan Jauh Mewah"],
    service_center: "Eksklusif (Mercedes-Benz PRO)"
  },
  {
    id: "mercedes-eqs-450",
    brand: "Mercedes-Benz",
    model: "EQS 450+",
    year: 2024,
    price_range: { min: 2984000000, max: 2984000000 },
    priceFormatted: "Rp 2.98 Milyar",
    battery_capacity: 107.8,
    range_claimed: 770,
    range_real_world: 650,
    charging_time: { ac: 10.0, dc: 0.5 },
    fastChargeTimeMins: 31,
    motor_power: 245,
    torque: 565,
    seating_capacity: 5,
    cargo_volume: 610,
    ground_clearance: 134,
    warranty: { years: 10, km: 250000 },
    made_in: "Germany",
    images: ["https://images.unsplash.com/photo-1689255767852-c62cbac6b5eb?q=80&w=1000&auto=format&fit=crop"],
    official_website: "https://www.mercedes-benz.co.id",
    dealer_network: ["Jakarta", "Surabaya", "Bandung", "Medan"],
    incentives: [],
    category: "sedan",
    bodyType: "Sedan",
    tags: ["luxury", "performance"],
    pros: ["Range terbaik di Indonesia (Nyaris 800km klaim)", "Hyperscreen sangat spektakuler", "Teknologi tercanggih"],
    cons: ["Sangat mahal", "Mobil sangat panjang"],
    suitability: ["Sultan", "Konglomerat", "Roadtrip Antar Kota"],
    service_center: "Eksklusif (Mercedes-Benz PRO)"
  }
];
